# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  default

steps:
- script: |
    mvn clean package
  displayName: "maven package"

- script: |
    mvn deploy
  displayName: "maven deploy"

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/target'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SpringFramework_fullsources'
    publishLocation: 'Container'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
